app/listings/views.py
from app import app, db
from flask import render_template, url_for, flash, redirect, request, jsonify, session, abort, Blueprint
from flask_login import current_user, login_required
from .forms import buyListingForm, createListingForm, unlistForm, relistForm
from app.models import User, Company, Address, Listing, CompanyListing, UserListing, Orders
from app.utils import getSession, saveImage
from datetime import datetime
import json

listings = Blueprint('listings', __name__)


#all the listings that the company / user has created
@listings.route('/account/listings', methods=('GET', 'POST'))
@login_required
def allListings():
    unlist = unlistForm()
    relist = relistForm()
    company = Company.query.filter_by(user_id = current_user.id).first()
    today = datetime.now()


    if company:
        listings = db.session.query(Listing, Address)\
            .join(CompanyListing, CompanyListing.listing_id == Listing.id)\
            .join(Company)\
            .join(Address)\
            .filter(CompanyListing.company_id == company.id)\
            .all()
    else:
        listings = db.session.query(Listing, Address)\
            .join(UserListing, UserListing.listing_id == Listing.id)\
            .join(User)\
            .join(Address)\
            .filter(UserListing.user_id == current_user.id)\
            .all()


    return render_template('account/listings.html',
                                listings = listings,
                                unlist = unlist,
                                relist = relist,
                                today = today,
                                header = True,
                                title = "account | listings")




#show a specific listing. Takes the ID of the listing that is being shown
#if the listingId doesnt exist, redirect to the home page, else show the listing
@listings.route('/listing/<int:listingId>', methods=('GET', 'POST'))
def viewListing(listingId):
    today = datetime.now()

    listing = Listing.query.get_or_404(listingId)

    company = db.session.query(Listing, Company, Address)\
        .join(CompanyListing, CompanyListing.listing_id == Listing.id)\
        .join(Company).join(Address)\
        .filter(Listing.sold.is_(False))\
        .filter(Listing.id == listingId)\
        .first()

    users = db.session.query(Listing, User, Address)\
            .join(UserListing, UserListing.listing_id == Listing.id)\
            .join(User).join(Address)\
            .filter(Listing.sold.is_(False))\
            .filter(Listing.id == listingId)\
            .first()

    #if the listingId doesnt exist
    if not company and not users:
        app.logger.error(f"Trying to access Listing #{listingId}, which doesn't exist")
        return redirect(url_for('main.home'))

    item = company if company else users

    #if the listing has expired (been brought or out of date)
    if item.Listing.sold or item.Listing.time < today:
        return redirect(url_for('main.home')) 

    form = buyListingForm()

    return render_template('listing.html',
                            today = today,
                            item = item,
                            form = form,
                            header = True,
                            title = 'listing')



#buy a specified listing
#only process the listing as brought if the form is valid and the listingId exists, else redirect
#when a listing is brought descrease its quanitity and mark it as sold if quantity <= 0
@listings.route('/listing/buy/<int:listingId>', methods=('GET', 'POST'))
@login_required
def buyListing(listingId):
    form = buyListingForm()

    if form.validate_on_submit():
        item = Listing.query.get_or_404(listingId)
        current = datetime.now()

        order = Orders(user_id = current_user.id, listing_id = item.id, time = current)

        item.quantity = item.quantity - 1 #reduce quantity
        if (item.quantity) <= 0: #check if sold
            item.sold = True

        db.session.add(order)
        db.session.commit()

        session['orders'], session['listings'],session['claimed'] = getSession()
        return redirect(url_for('orders.reciept', orderId = order.id))

    if form.errors:
        app.logger.warning("Error Buying Listing: " + str(form.errors))

    return redirect(url_for('listings.viewListing', listingId = listingId))



#create a listing to be placed on the application
#users and companies create listings on the same page, but using different subforms 
@listings.route('/account/create', methods=('GET', 'POST'))
@login_required
def createListing():
    form = createListingForm()
    company = Company.query.filter_by(user_id = current_user.id).first()

    if form.listing.validate_on_submit(): #if the shared subform is valid (containing the listing details)
        pictureFile = None
        if form.listing_image.image_data.data != '':
            pictureFile = form.listing_image.image_data.data

        if form.listing.price.data.replace(' ', '') == '':
            form.listing.price.data = 0

        #combine the date and time to form a datetime 
        date = datetime.combine(form.listing.date.data, form.listing.time.data)

        # Company create form (without address)
        if company: 
            listing = Listing(name = form.listing.lname.data,
                            price = form.listing.price.data,
                            description = form.listing.ldescription.data,
                            time = date,
                            quantity = form.listing.quantity.data,
                            image = pictureFile)
            db.session.add(listing)
            db.session.commit()

            company_listing = CompanyListing(company_id = company.id,
                                        listing_id = listing.id)
            db.session.add(company_listing)
            db.session.commit()

            #reset the session since listings increased
            session['orders'], session['listings'],session['claimed'] = getSession()
            flash("Listing created successfully")
            return redirect(url_for('main.home'))

        # User create form (with address)
        else:
            if form.address.validate(form): #if the users subform is valid (containing the address of the listing)
                listing = Listing(name = form.listing.lname.data,
                                price = form.listing.price.data,
                                description = form.listing.ldescription.data,
                                time = date,
                                quantity = form.listing.quantity.data,
                                image = pictureFile)

                address = Address(street1 = form.address.street1.data,
                                street2 = form.address.street2.data,
                                city = form.address.city.data,
                                state = form.address.state.data,
                                postal = form.address.postal.data,
                                country = form.address.country.data)

                db.session.add(listing)
                db.session.add(address)
                db.session.commit()

                user_listing = UserListing(user_id = current_user.id,
                                            listing_id = listing.id,
                                            address_id = address.id)
                db.session.add(user_listing)
                db.session.commit()

                #reset the session since listings increased
                session['orders'], session['listings'],session['claimed'] = getSession()
                flash("Listing created successfully")
                return redirect(url_for('main.home'))

    if form.errors:
        app.logger.warning("Error Creating Listing: " + str(form.errors))

    return render_template('account/create.html',
                            form = form,
                            header = True,
                            title = "account | create-listing")



@listings.route('/account/create/response-1', methods=('GET', 'POST'))
@login_required
def createResponse1():
    form = createListingForm()

    if form.listing.validate(form):
        data = {'lname': form.listing.lname.data,
                'ldescription': form.listing.ldescription.data,
                'price': form.listing.price.data,
                'date': form.listing.date.data,
                'time': form.listing.time.data,
                'quantity': form.listing.quantity.data}

        return json.dumps(data, default=str) #add image to the file here so it stays on potential reload

    if form.errors:
        app.logger.warning("Error Creating Listing: " + str(form.errors))

    return jsonify({'error': form.listing.errors})


@listings.route('/account/create/response-2', methods=('GET', 'POST'))
@login_required
def createResponse2():
    form = createListingForm()

    if form.listing_image.validate(form):
        pictureFile = None
        if (form.listing_image.image.data):
            pictureFile = saveImage(form.listing_image.image.data, 'listing_upload', 1000, 500)

        return jsonify({'image': pictureFile})

    if form.errors:
        app.logger.warning("Error Creating Listing: " + str(form.errors))

    return jsonify({'error': form.listing_image.errors})

@listings.route('/account/create/response-3', methods=('GET', 'POST'))
@login_required
def createResponse3():
    form = createListingForm()

    if form.address.validate(form):
        return jsonify({'street1': form.address.street1.data,
                        'street2': form.address.street2.data,
                        'city': form.address.city.data,
                        'state': form.address.state.data,
                        'postal': form.address.postal.data,
                        'country': form.address.country.data})

    if form.errors:
        app.logger.warning("Error Creating Listing: " + str(form.errors))

app/users/views.py
from flask import render_template, url_for, flash, redirect, request, session, abort, Blueprint
from app import app, db, bcrypt, client #so routes can use @app variable, import app and db variables from __init__.py
from .forms import loginForm
from app.models import User
from flask_login import login_user, logout_user, current_user, login_required
from app.utils import getSession, getGoogleProviderCfg
import requests
import json

users = Blueprint('users', __name__)

#log in the user and redirect them to the accounts page (if the requested to go there),
# else redirect to the home page
@users.route('/login', methods=('GET', 'POST'))
def login():
    if current_user.is_authenticated:
        return redirect(url_for('accounts.account'))

    form = loginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user: #we dont need to validate the users password, since this is done within the form validation
            login_user(user, remember = form.remember.data)

            session['orders'], session['listings'],session['claimed'] = getSession()

            nextPage = request.args.get('next') #get returns none if the next key doesnt exists (so it better than ['next'])
            flash("Successfully Logged In!")
            return redirect(nextPage) if nextPage else redirect(url_for('accounts.account'))

    if form.errors:
        app.logger.warning("Error Logging User In: " + str(form.errors))

    return render_template('login.html',
                            form = form,
                            header = True,
                            title = "login")


@users.route('/login/gsuite', methods=('GET', 'POST'))
def gsuite():
    google_provider_cfg = getGoogleProviderCfg()
    authorization_endpoint = google_provider_cfg["authorization_endpoint"]

    request_uri = client.prepare_request_uri(
        authorization_endpoint,
        redirect_uri=request.base_url + "/callback",
        scope=["openid", "email", "profile"],
    )
    return redirect(request_uri)


@users.route('/login/gsuite/callback', methods=('GET', 'POST'))
def callback():
    code = request.args.get("code")
  
    # Find out what URL to hit to get tokens that allow you to ask for
    # things on behalf of a user
    google_provider_cfg = getGoogleProviderCfg()
    token_endpoint = google_provider_cfg["token_endpoint"]

    # Prepare and send a request to get tokens! Yay tokens!
    token_url, headers, body = client.prepare_token_request(
        token_endpoint,
        authorization_response=request.url,
        redirect_url=request.base_url,
        code=code
    )
    token_response = requests.post(
        token_url,
        headers=headers,
        data=body,
        auth=(app.config['GOOGLE_LOGIN_CLIENT_ID'], app.config['GOOGLE_LOGIN_CLIENT_SECRET']),
    )

    # Parse the tokens!
    client.parse_request_body_response(json.dumps(token_response.json()))


    # Now that you have tokens (yay) let's find and hit the URL
    # from Google that gives you the user's profile information,
    # including their Google profile image and email
    userinfo_endpoint = google_provider_cfg["userinfo_endpoint"]
    uri, headers, body = client.add_token(userinfo_endpoint)
    userinfo_response = requests.get(uri, headers=headers, data=body)


    if userinfo_response.json().get("email_verified"):
        userId = userinfo_response.json()["sub"]
        userEmail = userinfo_response.json()["email"]
        userImage = userinfo_response.json()["picture"]
        userFirstName = userinfo_response.json()["given_name"]
        userLastName = userinfo_response.json()['family_name']

        user = User.query.filter_by(external_id=userId).first()

        if user:
            login_user(user, remember = False)
            session['orders'], session['listings'],session['claimed'] = getSession()

            nextPage = request.args.get('next') #get returns none if the next key doesnt exists (so it better than ['next'])
            
            flash("Successfully Logged In!")
            return redirect(nextPage) if nextPage else redirect(url_for('accounts.account'))

        # no account exists with the google id
        else:
            user = User.query.filter_by(email = userEmail).first()

            # if an account already exists with the same email, we can link the google account
            if user:
                user.external_id = userId
                db.session.commit()

                flash("Successfully Logged In!")
            else:
                user = User(first = userFirstName,
                            last = userLastName,
                            email = userEmail,
                            image = userImage,
                            external_type = 'google',
                            external_id = userId)
                db.session.add(user)
                db.session.commit()

                flash("Successfully Registered!")


            login_user(user, remember = False)
            session['orders'], session['listings'],session['claimed'] = getSession()

            return redirect(url_for('accounts.account'))

    else:
        app.logger.warning("Error Registering User: User email not available or not verified by Google")

        return "User email not available or not verified by Google.", 400


#end the user session and log the user out
@users.route('/logout')
def logout():
    logout_user()
    session.pop('claimed')
    flash("Successfully logged out!")
    return redirect(url_for('main.home'))

app/templates/claimed.html
{% extends "layout.html" %}
{% block content %}
    <div class="container py-5">
        <div class="py-2">
            <a class="font-weight-bold listing" href="{{ url_for('accounts.account') }}">Your Account</a> > <span class="font-weight-bold text-success">Orders to Claim</span>
        </div>

        {% for order in orders %}
            <div class="row">
                
                <div class="col mx-0 my-3 mx-sm-4 my-sm-4">
                    <h1 class="font-weight-bold px-4">Order ID #{{ order.Orders.id }}</h1>

                    <div class="account-navs text-center p-5">
                        <div class="py-4">
                            <h3>Order: {{ order.Listing.name }}</h3>
                            <h5>Collect By {{ order.Listing.time.strftime("%b %d %Y") }} at {{ order.Listing.time.strftime("%H:%M") }}</h5>
                            <a href="{{ url_for('orders.reciept', orderId = order.Orders.id) }}" class="btn btn-form">
                                View Reciept and Collection Location
                            </a>
                        </div>

                        <span>Only mark an order as claimed when you have actually collected it!</span>
                        <!-- <h3 class="font-weight-bold ">Create Listing</h3> -->
                        <form action="{{ url_for('orders.claimOrderClaimed', orderId = order.Orders.id) }}" method="POST" autocomplete="off">
                            {{ form.hidden_tag() }}
                            {{ form.submit(class="btn btn-form btn-register btn-lg m-3") }}
                        </form>
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>
{% endblock %}

app/templates/header.html
<ul class="nav justify-content-center" style="background-color: #8cbe64; ">
    <li class="nav-item text-uppercase">
        <!-- <a class="nav-link active" href="#">Open modal to choose location</a> -->
        <span class="nav-link font-weight-bold" style="color: white;">Help Prevent Food Waste, Use FoodFlogs!</span>
    </li>
</ul>

<nav class="navbar navbar-expand-lg navbar-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('main.home') }}">
            <img src="{{ url_for('static', filename='icons/logo.PNG') }}" width="120"/>
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <!-- <li class="nav-item">
                    <a class="nav-link" href="#">Household</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="#">Cafe's/Restraunts</a>
                </li> -->
            </ul>


            <ul class="navbar-nav">
                <!-- <li class="nav-item">
                    <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">
                        <img src="{{ url_for('static', filename='icons/search.png') }}" class="nav-img"/>
                    </a>
                </li> -->

                <li class="nav-item dropdown">
                    {% if current_user.is_authenticated %}
                        <a class="nav-link" href="#" tabindex="-1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img src="{{ url_for('static', filename='icons/user.png') }}" class="nav-img" data-toggle="tooltip" data-placement="bottom" title="{{ current_user.first }}  {{ current_user.last }}" />
                        </a>
                    {% else %}
                        <a class="nav-link" href="#" tabindex="-1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img src="{{ url_for('static', filename='icons/user.png') }}" class="nav-img" data-toggle="tooltip" data-placement="bottom" title="Account" />
                        </a>
                    {% endif %}

                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        {% if current_user.is_authenticated %}
                            <a class="dropdown-item" href="{{ url_for('accounts.account') }}">Account</a>
                            <a class="dropdown-item" href="{{ url_for('users.logout') }}">Logout</a>
                        {% else %}
                            <a class="dropdown-item" href="{{ url_for('users.login') }}">Login</a>
                            <a class="dropdown-item" href="{{ url_for('registration.register') }}">Register</a>
                        {% endif %}
                    </div>
                </li>

                {% if session.get('claimed') %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('orders.claimOrder') }}" tabindex="-1" aria-disabled="true">
                            <img src="{{ url_for('static', filename='icons/box.png') }}" class="nav-img" data-toggle="tooltip" data-placement="bottom" title="Orders to Claim!"/>
                            <span class="basket-count">{{ session.get('claimed') }}</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

app/templates/listing.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <div class="py-2">
            < <a class="font-weight-bold listing" href="{{ url_for('main.home') }}">Back to results</a>
        </div>

        <div class="card">
            <div class="img-container img-container-listing" style="background-image: url({{ item.Listing.image }});">
                <div class="img-overlay img-overlay-listing"></div>
            </div>

            <div class="card-body px-4 py-3">
                {% if item.Listing.company %}
                    <div class="position-absolute listing_company d-flex align-items-center">
                        <!-- <div><img class="rounded-circle account-img" id="company-image" src="{{ url_for('static', filename='uploads/company_profile/') }}{{ item.Company.image }}"></div> -->
                        <div><img class="rounded-circle account-img" id="company-image" src="{{ item.Company.image }}"></div>
                        
                        <div><span class="px-2 d-block font-weight-bold">{{ item.Company.name }}</span></div>
                    </div>	
                    <span>{{ item.Company.typeof }}</span>
                {% else %}
                    <div class="position-absolute listing_company d-flex align-items-center">
                        <!-- <div><img class="rounded-circle account-img" id="company-image" src="{{ url_for('static', filename='uploads/profile_pics/') }}{{ item.User.image }}"></div> -->
                        <div><img class="rounded-circle account-img" id="company-image" src="{{ item.User.image }}"></div>
                        
                        <div><span class="px-2 d-block font-weight-bold">{{ item.User.first }} {{ item.User.last }}</span></div>
                    </div>	
                {% endif %}

                <h3 class="card-title m-0">{{ item.Listing.name }}</h3>

                
            </div>

            <ul class="list-group list-group-flush">
                <li class="list-group-item list-group-item-border-none">
                    <div class="row">
                        <div class="col">
                            <img src="{{ url_for('static', filename='icons/time.png') }}" width="20">
                            {% set time = item.Listing.time - today %}
                            {{ time|strftime }}
                        </div>
                    
                        <div class="col text-right font-weight-bold ">
                            £{{ item.Listing.price }}
                        </div>
                    </div>
                </li>
            </ul>

            <div class="card-header"></div>

            <ul class="list-group list-group-flush">
                <li class="list-group-item list-group-item-border-none">
                    <h5 class="font-weight-bold">What you could get</h5>
                    <p>
                        {{ item.Listing.description }}
                    </p>
                </li>

                <li class="list-group-item text-center font-weight-bold">
                    <button type="button" data-toggle="modal" data-target="#exampleModal" class="btn btn-form">Ingredients & allergens</button>
                </li>
            </ul>

            <div class="card-header"></div>

            <div class="card-body">
                <h5 class="font-weight-bold">Where To Collect</h5>
                <p id="address">
                    {{ item.Address.street1 }}, {{ item.Address.street2 }}, {{item.Address.city}}, {{item.Address.postal}}, {{ item.Address.country }}
                </p>
                <div id="googleMap" style="height: 250px; "></div>
            </div>

            <div class="card-header"></div>

            <div class="card-body">
                <form action="{{ url_for('listings.buyListing', listingId = item.Listing.id) }}" method="POST" autocomplete="off">
                    {{ form.hidden_tag() }}
                    <div class="form-group text-center my-2">
                        {{ form.submit(class="btn btn-form btn-register") }}
                    </div>
                </form>
            </div>
        </div>
        
        <div class="p-4"></div>


        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Ingredients & allergens</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        {% if item.Listing.company %}
                            We cant predict what {{ item.Company.name }} has put in their listing as it depends on them at the time of sale.
                            If you are concerned please ask them.
                        {% else %}
                            We cant predict what {{ item.User.first }} {{ item.User.last }} has put in their listing as it depends on them at the time of sale.
                            If you are concerned please ask them.
                        {% endif %}


                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-form" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript" src="{{ url_for('static', filename='js/modules/mapFunctions.js') }}?version=0" defer></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDaTLbLs6MliN_6Oe9lW7ucid4DIE6ZscY&callback=initMap" defer></script>

{% endblock %}

app/templates/login.html
{% extends "layout.html" %}
{% block content %}
    {{ form.email.errors }}
    <div class="container">
        <div class="p-3 m-md-2 text-center">
            <div class="col-md-8 p-lg-4 mx-auto my-3">
                <h1>Login</h1>

                <a href="{{ url_for('users.gsuite') }}">  Login with Google </a>

                <form action="" method="POST" autocomplete="on">
                    {{ form.hidden_tag() }} 

                    <div class="form-group">
                        {{ form.email.label(class="d-block text-left pt-2") }}
                        {{ form.email(class = "form-control form-control-bold") }}

                        {% if form.email.errors %}
                            {% for error in form.email.errors %}
                                <small id="first-error" class="form-text text-muted form-error">{{ error }}</small>
                            {% endfor %}
                        {% endif %}
                    </div>

                    <div class="form-group">
                        {{ form.password.label(class="d-block text-left pt-2") }}
                        {{ form.password(class = "form-control form-control-bold", autocomplete="on") }}

                        {% if form.password.errors %}
                            {% for error in form.password.errors %}
                                <small id="first-error" class="form-text text-muted form-error">{{ error }}</small>
                            {% endfor %}
                        {% endif %}
                    </div>

                    <div class="form-group form-check text-left">
                        {{ form.remember(class = "form-check-input") }}
                        {{ form.remember.label(class="d-block text-left mt-4") }}
                    </div>
                    
                    {{ form.submit(class = "btn btn-form btn-register") }}

                </form>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/register.html
{% extends "layout.html" %}
{% block content %}

    <div class="container"> 
        <div class="p-3 m-md-2 text-center">
            <div class="col-md-8 p-lg-4 mx-auto my-4"> 

                <h1>Register your interest</h1>
                <span>Join the fight against food waste!</span>

                <a href="{{ url_for('users.gsuite') }}">  Sign up with Google </a>

                <div class="my-5">
                    <a class="btn btn-form btn-register m-3" href="{{ url_for('registration.registerCompany')}}">Im a cafe / restraunt!</a>
                    <a class="btn btn-form btn-register m-3" href="{{ url_for('registration.registerPersonal')}}">Im fighting food waste on my own!</a>
                </div>
            </div>
        </div>
    </div>

    <!-- <img src="{{ url_for('static', filename='icons/tree.png') }}"/> -->
{% endblock %}